# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookine', '0002_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('delivery', models.IntegerField(default=0)),
            ],
        ),
    ]
